name: CPI Deploy Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo command.
        run: |
         echo "🎉 < hi"
         echo "🐧 < hello"
         echo "🔎 < hello"
         echo "💡 < hello" 
         echo "🖥️ < hello"
