name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 < hi"
      - run: echo "🐧 < hello"
      - run: echo "🔎 < hello"
      - run: echo "💡 < hello" 
      - run: echo "🖥️ < hello"
      - run: | 
          IP_ADDRESS=`curl ifconfig.io`
          echo $IP_ADDRESS
